spring:
  application:
    name: config-dev

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-register-with-eureka: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

